import type { FoodItem } from "@/lib/types";

export const FOOD_DB: FoodItem[] = [
  { name: "Hähnchenbrust", aliases: ["haehnchenbrust","huhnbrust","huhn","chicken","haehnchen","hähnchen","chicken breast"], kcal: 165, protein: 31, carbs: 0, fat: 3.6 },
  { name: "Hähnchenschenkel", aliases: ["haehnchenschenkel","huhnschenkel","chicken thigh"], kcal: 185, protein: 22, carbs: 0, fat: 11 },
  { name: "Hähnchenflügel", aliases: ["chicken wings","wings","fluegel"], kcal: 203, protein: 18, carbs: 0, fat: 14 },
  { name: "Hähnchenhack", aliases: ["haehnchenhack","chicken mince"], kcal: 143, protein: 20, carbs: 0, fat: 7 },
  { name: "Putenbrust", aliases: ["pute","truthahn","turkey","putenfilet"], kcal: 135, protein: 29, carbs: 0, fat: 1.5 },
  { name: "Putenhack", aliases: ["putenhackfleisch"], kcal: 150, protein: 20, carbs: 0, fat: 8 },
  { name: "Rinderhack", aliases: ["hackfleisch","hack","hackfleisch rind","ground beef"], kcal: 250, protein: 26, carbs: 0, fat: 16 },
  { name: "Rinderhack mager", aliases: ["mageres hack","lean beef"], kcal: 170, protein: 24, carbs: 0, fat: 8 },
  { name: "Rindersteak", aliases: ["steak","rind","rinderfilet","rumpsteak"], kcal: 180, protein: 27, carbs: 0, fat: 8 },
  { name: "Rinderfilet", aliases: ["filet steak"], kcal: 160, protein: 28, carbs: 0, fat: 5 },
  { name: "Schweinefilet", aliases: ["schwein","schweinefleisch","pork tenderloin"], kcal: 143, protein: 21, carbs: 0, fat: 6 },
  { name: "Schweineschnitzel", aliases: ["schnitzel","schweineschnitzel"], kcal: 160, protein: 22, carbs: 0, fat: 7 },
  { name: "Kasseler", aliases: ["kassler","kasselerbraten"], kcal: 180, protein: 18, carbs: 0, fat: 12 },
  { name: "Speck", aliases: ["bacon"], kcal: 540, protein: 12, carbs: 0, fat: 55 },
  { name: "Schinken", aliases: ["kochschinken","hinterschinken"], kcal: 110, protein: 20, carbs: 1, fat: 3 },
  { name: "Salami", aliases: [], kcal: 400, protein: 20, carbs: 1, fat: 35 },
  { name: "Leberwurst", aliases: [], kcal: 320, protein: 14, carbs: 2, fat: 28 },
  { name: "Weißwurst", aliases: ["weisswurst"], kcal: 270, protein: 11, carbs: 1, fat: 24, pieceGrams: 100 },
  { name: "Bratwurst", aliases: ["grillwurst"], kcal: 300, protein: 14, carbs: 1, fat: 27, pieceGrams: 100 },
  { name: "Currywurst", aliases: [], kcal: 280, protein: 12, carbs: 8, fat: 22, pieceGrams: 150 },
  { name: "Hackbällchen", aliases: ["frikadelle","boulette","fleischbällchen"], kcal: 220, protein: 18, carbs: 5, fat: 14 },
  { name: "Gyros", aliases: ["dönerfleisch","doenerfleisch"], kcal: 230, protein: 20, carbs: 2, fat: 16 },
  { name: "Döner", aliases: ["doener","doner","kebap","kebab"], kcal: 250, protein: 15, carbs: 20, fat: 12, pieceGrams: 350 },
  { name: "Lachs", aliases: ["salmon"], kcal: 208, protein: 20, carbs: 0, fat: 13 },
  { name: "Lachs geräuchert", aliases: ["raucherlachs"], kcal: 180, protein: 22, carbs: 0, fat: 10 },
  { name: "Thunfisch", aliases: ["tuna","thunfischdose","thunfisch in wasser"], kcal: 116, protein: 26, carbs: 0, fat: 1 },
  { name: "Thunfisch in Öl", aliases: ["thunfisch oel"], kcal: 190, protein: 25, carbs: 0, fat: 10 },
  { name: "Kabeljau", aliases: ["fisch","weißfisch","weissfisch","cod"], kcal: 82, protein: 18, carbs: 0, fat: 0.7 },
  { name: "Pangasius", aliases: [], kcal: 90, protein: 15, carbs: 0, fat: 3 },
  { name: "Forelle", aliases: ["trout"], kcal: 120, protein: 20, carbs: 0, fat: 4 },
  { name: "Makrele", aliases: [], kcal: 190, protein: 18, carbs: 0, fat: 13 },
  { name: "Sardinen", aliases: ["sardine"], kcal: 180, protein: 20, carbs: 0, fat: 11 },
  { name: "Garnelen", aliases: ["shrimp","krebs","prawns"], kcal: 99, protein: 24, carbs: 0.2, fat: 0.3 },
  { name: "Muscheln", aliases: [], kcal: 86, protein: 12, carbs: 3, fat: 2 },
  { name: "Sushi", aliases: ["maki","nigiri"], kcal: 150, protein: 6, carbs: 25, fat: 3 },
  { name: "Fischstäbchen", aliases: ["fischstaebchen"], kcal: 200, protein: 12, carbs: 18, fat: 9, pieceGrams: 30 },
  { name: "Ei", aliases: ["eier","hühnerei","huehnerei","egg"], kcal: 155, protein: 13, carbs: 1.1, fat: 11, pieceGrams: 60 },
  { name: "Eiklar", aliases: ["eiweiß","eiweiss","egg white"], kcal: 52, protein: 11, carbs: 0.7, fat: 0.2 },
  { name: "Eigelb", aliases: ["dotter","egg yolk"], kcal: 320, protein: 16, carbs: 1.6, fat: 27 },
  { name: "Magerquark", aliases: ["quark","speisequark","magerquark 0,2%"], kcal: 67, protein: 12, carbs: 4, fat: 0.3 },
  { name: "Quark 20%", aliases: ["quark 20","vollfettquark"], kcal: 140, protein: 10, carbs: 3.5, fat: 10 },
  { name: "Skyr", aliases: ["skyr natur","skyr natural"], kcal: 63, protein: 11, carbs: 4, fat: 0.2 },
  { name: "Griechischer Joghurt", aliases: ["joghurt","griechisch","greek yogurt","jogurt","joghurt natur"], kcal: 97, protein: 9, carbs: 3.6, fat: 5 },
  { name: "Joghurt 1,5%", aliases: ["magermilchjoghurt"], kcal: 50, protein: 4.5, carbs: 5, fat: 1.5 },
  { name: "Hüttenkäse", aliases: ["huettenkaese","cottage","cottage cheese"], kcal: 98, protein: 11, carbs: 3.4, fat: 4.3 },
  { name: "Frischkäse light", aliases: ["frischkaese","cream cheese light"], kcal: 140, protein: 10, carbs: 4, fat: 10 },
  { name: "Frischkäse", aliases: ["frischkaese natur"], kcal: 240, protein: 6, carbs: 3, fat: 23 },
  { name: "Milch 1,5%", aliases: ["milch","low fat milk","fettarme milch"], kcal: 47, protein: 3.4, carbs: 4.8, fat: 1.5 },
  { name: "Milch 3,5%", aliases: ["vollmilch"], kcal: 64, protein: 3.3, carbs: 4.7, fat: 3.5 },
  { name: "Hafermilch", aliases: ["oat milk","haferdrink"], kcal: 46, protein: 1, carbs: 6.7, fat: 1.5 },
  { name: "Mandelmilch", aliases: ["almond milk"], kcal: 25, protein: 0.6, carbs: 1, fat: 1.8 },
  { name: "Sojamilch", aliases: ["soy milk"], kcal: 40, protein: 3, carbs: 2.5, fat: 2 },
  { name: "Buttermilch", aliases: [], kcal: 35, protein: 3.5, carbs: 4, fat: 0.5 },
  { name: "Kefir", aliases: [], kcal: 50, protein: 3.3, carbs: 4.5, fat: 2 },
  { name: "Proteinpulver", aliases: ["whey","proteinshake","shake","protein pulver","eiweißpulver","eiweisspulver","whey protein"], kcal: 380, protein: 80, carbs: 6, fat: 5, pieceGrams: 30 },
  { name: "Casein", aliases: ["casein protein","nachtprotein"], kcal: 360, protein: 80, carbs: 5, fat: 2, pieceGrams: 30 },
  { name: "Käse", aliases: ["kaese","gouda","schnittkäse","schnittkaese"], kcal: 350, protein: 25, carbs: 1, fat: 27 },
  { name: "Gouda light", aliases: ["kaese light"], kcal: 270, protein: 28, carbs: 1, fat: 17 },
  { name: "Mozzarella", aliases: ["mozzarella light"], kcal: 280, protein: 18, carbs: 2, fat: 22 },
  { name: "Mozzarella light", aliases: [], kcal: 160, protein: 20, carbs: 2, fat: 8 },
  { name: "Feta", aliases: ["schafskäse","schafskaese"], kcal: 264, protein: 14, carbs: 4, fat: 21 },
  { name: "Parmesan", aliases: [], kcal: 400, protein: 35, carbs: 0, fat: 28 },
  { name: "Cheddar", aliases: [], kcal: 400, protein: 25, carbs: 1, fat: 33 },
  { name: "Emmentaler", aliases: [], kcal: 380, protein: 28, carbs: 0, fat: 30 },
  { name: "Camembert", aliases: [], kcal: 300, protein: 20, carbs: 0, fat: 24 },
  { name: "Schmelzkäse", aliases: ["schmelzkaese"], kcal: 280, protein: 12, carbs: 5, fat: 24 },
  { name: "Haferflocken", aliases: ["hafer","oats","porridge","oatmeal","kernige haferflocken"], kcal: 370, protein: 13.5, carbs: 59, fat: 7 },
  { name: "Haferflocken zart", aliases: ["zarte haferflocken"], kcal: 365, protein: 13, carbs: 58, fat: 7 },
  { name: "Reis gekocht", aliases: ["reis","basmati","reis gekocht","jasminreis"], kcal: 130, protein: 2.7, carbs: 28, fat: 0.3 },
  { name: "Reis roh", aliases: ["reis ungekoccht","rohreis","trockenreis"], kcal: 360, protein: 7, carbs: 79, fat: 0.6 },
  { name: "Vollkornreis gekocht", aliases: [], kcal: 120, protein: 3, carbs: 25, fat: 1 },
  { name: "Nudeln gekocht", aliases: ["nudeln","pasta","spaghetti","penne","fusilli"], kcal: 157, protein: 5.8, carbs: 30, fat: 0.9 },
  { name: "Nudeln roh", aliases: ["trockennudeln","pasta roh"], kcal: 350, protein: 13, carbs: 71, fat: 1.5 },
  { name: "Vollkornnudeln gekocht", aliases: [], kcal: 140, protein: 6, carbs: 26, fat: 1.5 },
  { name: "Kartoffeln", aliases: ["kartoffel","potato","festkochend"], kcal: 77, protein: 2, carbs: 17, fat: 0.1 },
  { name: "Süßkartoffel", aliases: ["suesskartoffel","sweet potato"], kcal: 86, protein: 1.6, carbs: 20, fat: 0.1 },
  { name: "Ofenkartoffel", aliases: ["jacket potato"], kcal: 93, protein: 2.5, carbs: 21, fat: 0.1, pieceGrams: 200 },
  { name: "Kartoffelpüree", aliases: ["kartoffelpüree","püree","puree","kartoffelbrei"], kcal: 83, protein: 2, carbs: 13, fat: 2.8 },
  { name: "Pommes", aliases: ["pommes frites","french fries"], kcal: 300, protein: 3.5, carbs: 40, fat: 15 },
  { name: "Brot", aliases: ["weizenbrot","toast","scheibe brot","weißbrot"], kcal: 265, protein: 9, carbs: 49, fat: 3.2, pieceGrams: 40 },
  { name: "Vollkornbrot", aliases: ["vollkorn","graubrot","vollkornbrot"], kcal: 250, protein: 8, carbs: 43, fat: 3.5, pieceGrams: 45 },
  { name: "Roggenbrot", aliases: [], kcal: 240, protein: 7, carbs: 45, fat: 1.5, pieceGrams: 45 },
  { name: "Knäckebrot", aliases: ["knaeckebrot","knäcke"], kcal: 360, protein: 10, carbs: 70, fat: 2.5, pieceGrams: 10 },
  { name: "Brötchen", aliases: ["broetchen","semmel","schrippe"], kcal: 270, protein: 8, carbs: 52, fat: 2.5, pieceGrams: 60 },
  { name: "Laugenbrezel", aliases: ["brezel","breze"], kcal: 300, protein: 8, carbs: 55, fat: 5, pieceGrams: 70 },
  { name: "Reiswaffeln", aliases: ["reiswaffel"], kcal: 390, protein: 8, carbs: 82, fat: 3, pieceGrams: 8 },
  { name: "Cornflakes", aliases: [], kcal: 370, protein: 7, carbs: 84, fat: 1 },
  { name: "Müsli", aliases: ["muesli","crunchy"], kcal: 380, protein: 9, carbs: 65, fat: 8 },
  { name: "Proteinmüsli", aliases: [], kcal: 360, protein: 25, carbs: 40, fat: 8 },
  { name: "Quinoa gekocht", aliases: ["quinoa"], kcal: 120, protein: 4.4, carbs: 21, fat: 1.9 },
  { name: "Couscous gekocht", aliases: [], kcal: 112, protein: 3.8, carbs: 23, fat: 0.2 },
  { name: "Bulgur gekocht", aliases: [], kcal: 100, protein: 3.5, carbs: 20, fat: 0.3 },
  { name: "Polenta", aliases: [], kcal: 90, protein: 2, carbs: 18, fat: 0.5 },
  { name: "Tortilla", aliases: ["wrap","weizenwrap"], kcal: 300, protein: 8, carbs: 50, fat: 7, pieceGrams: 60 },
  { name: "Pita", aliases: ["pitabrot"], kcal: 275, protein: 9, carbs: 55, fat: 1.5, pieceGrams: 60 },
  { name: "Kichererbsen", aliases: ["kichererbse","chickpeas"], kcal: 160, protein: 9, carbs: 27, fat: 2.6 },
  { name: "Linsen gekocht", aliases: ["linsen","rote linsen"], kcal: 115, protein: 9, carbs: 20, fat: 0.4 },
  { name: "Bohnen gekocht", aliases: ["weiße bohnen","bohnen"], kcal: 120, protein: 8, carbs: 20, fat: 0.5 },
  { name: "Kidneybohnen", aliases: [], kcal: 125, protein: 8.5, carbs: 21, fat: 0.5 },
  { name: "schwarze Bohnen", aliases: [], kcal: 130, protein: 9, carbs: 23, fat: 0.5 },
  { name: "Edamame", aliases: ["sojabohnen"], kcal: 120, protein: 11, carbs: 9, fat: 5 },
  { name: "Tofu", aliases: ["tofu natur"], kcal: 120, protein: 12, carbs: 2, fat: 7 },
  { name: "Tofu geräuchert", aliases: [], kcal: 140, protein: 14, carbs: 2, fat: 8 },
  { name: "Tempeh", aliases: [], kcal: 190, protein: 19, carbs: 9, fat: 11 },
  { name: "Hummus", aliases: ["humus"], kcal: 170, protein: 7, carbs: 14, fat: 10 },
  { name: "Brokkoli", aliases: ["broccoli"], kcal: 34, protein: 2.8, carbs: 7, fat: 0.4 },
  { name: "Blumenkohl", aliases: [], kcal: 25, protein: 2, carbs: 5, fat: 0.3 },
  { name: "Spinat", aliases: [], kcal: 23, protein: 2.9, carbs: 3.6, fat: 0.4 },
  { name: "Grünkohl", aliases: ["gruenkohl"], kcal: 50, protein: 4, carbs: 9, fat: 0.7 },
  { name: "Salat", aliases: ["blattsalat","eisbergsalat","romanasalat"], kcal: 15, protein: 1.2, carbs: 2.5, fat: 0.2 },
  { name: "Tomate", aliases: ["tomaten"], kcal: 18, protein: 0.9, carbs: 3.9, fat: 0.2, pieceGrams: 100 },
  { name: "Gurke", aliases: [], kcal: 12, protein: 0.6, carbs: 2, fat: 0.1, pieceGrams: 300 },
  { name: "Paprika", aliases: ["peperoni"], kcal: 30, protein: 1, carbs: 6, fat: 0.3, pieceGrams: 150 },
  { name: "Zwiebel", aliases: ["zwiebeln"], kcal: 40, protein: 1.1, carbs: 9, fat: 0.1, pieceGrams: 100 },
  { name: "Knoblauch", aliases: [], kcal: 150, protein: 6, carbs: 33, fat: 0.5 },
  { name: "Karotte", aliases: ["karotten","möhre","moehre"], kcal: 41, protein: 0.9, carbs: 10, fat: 0.2, pieceGrams: 80 },
  { name: "Sellerie", aliases: [], kcal: 14, protein: 0.7, carbs: 3, fat: 0.2 },
  { name: "Zucchini", aliases: [], kcal: 17, protein: 1.2, carbs: 3.1, fat: 0.3 },
  { name: "Aubergine", aliases: ["eggplant"], kcal: 25, protein: 1, carbs: 6, fat: 0.2 },
  { name: "Champignons", aliases: ["pilze","mushroom","weißpilze"], kcal: 22, protein: 3.1, carbs: 3.3, fat: 0.3 },
  { name: "Mais", aliases: ["zuckermais"], kcal: 90, protein: 3, carbs: 19, fat: 1.2 },
  { name: "Erbsen", aliases: [], kcal: 80, protein: 5, carbs: 14, fat: 0.4 },
  { name: "Spargel", aliases: [], kcal: 20, protein: 2, carbs: 3.5, fat: 0.2 },
  { name: "Rosenkohl", aliases: [], kcal: 43, protein: 3.5, carbs: 9, fat: 0.3 },
  { name: "Kohlrabi", aliases: [], kcal: 27, protein: 1.7, carbs: 6, fat: 0.1 },
  { name: "Rote Bete", aliases: ["rote bete","rotebeete"], kcal: 43, protein: 1.6, carbs: 10, fat: 0.2 },
  { name: "Avocado", aliases: [], kcal: 160, protein: 2, carbs: 9, fat: 15, pieceGrams: 150 },
  { name: "Oliven", aliases: [], kcal: 145, protein: 1, carbs: 4, fat: 15 },
  { name: "Sauerkraut", aliases: [], kcal: 20, protein: 1, carbs: 4, fat: 0.1 },
  { name: "Gemüsemischung", aliases: ["gemuese","gemüse","tk gemüse"], kcal: 35, protein: 2, carbs: 6, fat: 0.3 },
  { name: "Banane", aliases: ["bananen"], kcal: 89, protein: 1.1, carbs: 23, fat: 0.3, pieceGrams: 120 },
  { name: "Apfel", aliases: ["äpfel","aepfel","apples"], kcal: 52, protein: 0.3, carbs: 14, fat: 0.2, pieceGrams: 160 },
  { name: "Orange", aliases: ["apfelsine","orangen"], kcal: 47, protein: 0.9, carbs: 12, fat: 0.1, pieceGrams: 150 },
  { name: "Birne", aliases: [], kcal: 57, protein: 0.4, carbs: 15, fat: 0.1, pieceGrams: 170 },
  { name: "Kiwi", aliases: [], kcal: 61, protein: 1.1, carbs: 15, fat: 0.5, pieceGrams: 75 },
  { name: "Mango", aliases: [], kcal: 60, protein: 0.8, carbs: 15, fat: 0.4 },
  { name: "Ananas", aliases: [], kcal: 50, protein: 0.5, carbs: 13, fat: 0.1 },
  { name: "Wassermelone", aliases: ["melone"], kcal: 30, protein: 0.6, carbs: 8, fat: 0.2 },
  { name: "Honigmelone", aliases: [], kcal: 35, protein: 0.8, carbs: 8, fat: 0.2 },
  { name: "Erdbeeren", aliases: ["erdbeere"], kcal: 32, protein: 0.7, carbs: 8, fat: 0.3 },
  { name: "Blaubeeren", aliases: ["heidelbeere","heidelbeeren","blueberries"], kcal: 57, protein: 0.7, carbs: 14, fat: 0.3 },
  { name: "Himbeeren", aliases: [], kcal: 52, protein: 1.2, carbs: 12, fat: 0.7 },
  { name: "Brombeeren", aliases: [], kcal: 43, protein: 1.4, carbs: 10, fat: 0.5 },
  { name: "Trauben", aliases: ["weintrauben"], kcal: 69, protein: 0.7, carbs: 18, fat: 0.2 },
  { name: "Pfirsich", aliases: [], kcal: 39, protein: 0.9, carbs: 10, fat: 0.3, pieceGrams: 150 },
  { name: "Nektarine", aliases: [], kcal: 44, protein: 1, carbs: 11, fat: 0.3, pieceGrams: 140 },
  { name: "Pflaume", aliases: ["zwetschge"], kcal: 46, protein: 0.7, carbs: 11, fat: 0.3 },
  { name: "Kirsche", aliases: ["kirschen"], kcal: 63, protein: 1, carbs: 16, fat: 0.2 },
  { name: "Cranberry", aliases: ["cranberries"], kcal: 46, protein: 0.4, carbs: 12, fat: 0.1 },
  { name: "Datteln", aliases: ["dattel"], kcal: 277, protein: 2, carbs: 75, fat: 0.2, pieceGrams: 8 },
  { name: "Rosinen", aliases: [], kcal: 299, protein: 3, carbs: 79, fat: 0.5 },
  { name: "Feigen getrocknet", aliases: [], kcal: 250, protein: 3, carbs: 64, fat: 1 },
  { name: "Beerenmix", aliases: ["beeren","beerenmischung"], kcal: 45, protein: 1, carbs: 10, fat: 0.4 },
  { name: "Mandeln", aliases: ["mandel"], kcal: 580, protein: 21, carbs: 22, fat: 50 },
  { name: "Walnüsse", aliases: ["walnuss"], kcal: 650, protein: 15, carbs: 14, fat: 65 },
  { name: "Cashew", aliases: ["cashews"], kcal: 580, protein: 18, carbs: 30, fat: 44 },
  { name: "Erdnüsse", aliases: ["erdnuss","peanuts"], kcal: 570, protein: 25, carbs: 16, fat: 49 },
  { name: "Haselnüsse", aliases: [], kcal: 630, protein: 14, carbs: 17, fat: 61 },
  { name: "Pistazien", aliases: [], kcal: 560, protein: 20, carbs: 28, fat: 45 },
  { name: "Sonnenblumenkerne", aliases: [], kcal: 580, protein: 20, carbs: 20, fat: 50 },
  { name: "Kürbiskerne", aliases: ["kuerbiskerne"], kcal: 560, protein: 30, carbs: 15, fat: 45 },
  { name: "Chiasamen", aliases: ["chia"], kcal: 486, protein: 17, carbs: 42, fat: 31 },
  { name: "Leinsamen", aliases: [], kcal: 534, protein: 18, carbs: 29, fat: 42 },
  { name: "Sesam", aliases: [], kcal: 570, protein: 18, carbs: 23, fat: 50 },
  { name: "Erdnussbutter", aliases: ["peanut butter"], kcal: 590, protein: 25, carbs: 20, fat: 50 },
  { name: "Mandelmus", aliases: ["mandelbutter"], kcal: 650, protein: 21, carbs: 20, fat: 56 },
  { name: "Nussmix", aliases: [], kcal: 600, protein: 18, carbs: 20, fat: 52 },
  { name: "Olivenöl", aliases: ["oliven oel","olive oil"], kcal: 884, protein: 0, carbs: 0, fat: 100 },
  { name: "Rapsöl", aliases: ["rapsoel"], kcal: 884, protein: 0, carbs: 0, fat: 100 },
  { name: "Butter", aliases: [], kcal: 750, protein: 0.7, carbs: 0.5, fat: 83 },
  { name: "Margarine", aliases: [], kcal: 720, protein: 0.2, carbs: 0.5, fat: 80 },
  { name: "Kokosöl", aliases: ["kokosoel"], kcal: 860, protein: 0, carbs: 0, fat: 100 },
  { name: "Mayonnaise", aliases: ["mayo"], kcal: 680, protein: 1, carbs: 1, fat: 75 },
  { name: "Mayonnaise light", aliases: ["mayo light"], kcal: 280, protein: 1, carbs: 8, fat: 28 },
  { name: "Pizza Margherita", aliases: ["pizza"], kcal: 250, protein: 11, carbs: 30, fat: 9, pieceGrams: 300 },
  { name: "Pasta Bolognese", aliases: ["bolognese","spaghetti bolognese"], kcal: 150, protein: 8, carbs: 18, fat: 5 },
  { name: "Lasagne", aliases: [], kcal: 160, protein: 9, carbs: 15, fat: 7 },
  { name: "Burger", aliases: ["hamburger","cheeseburger"], kcal: 280, protein: 15, carbs: 25, fat: 14, pieceGrams: 200 },
  { name: "Käsespätzle", aliases: ["kaesespaetzle","spätzle"], kcal: 220, protein: 10, carbs: 25, fat: 10 },
  { name: "Eintopf", aliases: ["gemüseeintopf"], kcal: 80, protein: 4, carbs: 10, fat: 2 },
  { name: "Gulasch", aliases: [], kcal: 140, protein: 12, carbs: 5, fat: 8 },
  { name: "Chili con Carne", aliases: ["chili"], kcal: 130, protein: 10, carbs: 12, fat: 5 },
  { name: "Reispfanne", aliases: [], kcal: 140, protein: 8, carbs: 18, fat: 4 },
  { name: "Nudelsalat", aliases: [], kcal: 180, protein: 6, carbs: 20, fat: 8 },
  { name: "Kartoffelsalat", aliases: [], kcal: 150, protein: 2, carbs: 15, fat: 9 },
  { name: "Leberkäse", aliases: ["leberkaese","fleischkäse"], kcal: 280, protein: 13, carbs: 2, fat: 24, pieceGrams: 80 },
  { name: "Frikadelle", aliases: ["boulette"], kcal: 250, protein: 16, carbs: 8, fat: 17, pieceGrams: 100 },
  { name: "Maultaschen", aliases: [], kcal: 180, protein: 9, carbs: 20, fat: 7 },
  { name: "Knödel", aliases: ["knoedel","semmelknödel"], kcal: 140, protein: 4, carbs: 25, fat: 3 },
  { name: "Kaiserschmarrn", aliases: [], kcal: 220, protein: 7, carbs: 30, fat: 8 },
  { name: "Pfannkuchen", aliases: ["eierkuchen","crepe"], kcal: 200, protein: 7, carbs: 25, fat: 8, pieceGrams: 80 },
  { name: "Waffeln", aliases: [], kcal: 300, protein: 6, carbs: 40, fat: 13 },
  { name: "Croissant", aliases: [], kcal: 400, protein: 8, carbs: 45, fat: 21, pieceGrams: 60 },
  { name: "Proteinpudding", aliases: ["high protein pudding","protein pudding"], kcal: 80, protein: 10, carbs: 6, fat: 1.5, pieceGrams: 200 },
  { name: "Proteinriegel", aliases: ["protein bar","riegel"], kcal: 350, protein: 25, carbs: 30, fat: 12, pieceGrams: 60 },
  { name: "Proteinjoghurt", aliases: [], kcal: 70, protein: 10, carbs: 5, fat: 1, pieceGrams: 150 },
  { name: "Skyr Vanille", aliases: ["skyr mit geschmack"], kcal: 80, protein: 10, carbs: 8, fat: 0.3 },
  { name: "Low Carb Brot", aliases: [], kcal: 180, protein: 15, carbs: 10, fat: 8, pieceGrams: 40 },
  { name: "Kaffee schwarz", aliases: ["kaffee","espresso","americano"], kcal: 2, protein: 0.1, carbs: 0, fat: 0, pieceGrams: 200 },
  { name: "Cappuccino", aliases: [], kcal: 40, protein: 2, carbs: 4, fat: 2, pieceGrams: 180 },
  { name: "Latte Macchiato", aliases: [], kcal: 55, protein: 3, carbs: 5, fat: 2.5, pieceGrams: 250 },
  { name: "Tee", aliases: ["schwarztee","grüner tee","gruener tee"], kcal: 1, protein: 0, carbs: 0, fat: 0, pieceGrams: 200 },
  { name: "Apfelsaft", aliases: [], kcal: 46, protein: 0.1, carbs: 11, fat: 0.1 },
  { name: "Orangensaft", aliases: [], kcal: 45, protein: 0.7, carbs: 10, fat: 0.2 },
  { name: "Cola", aliases: ["coca cola","coke"], kcal: 42, protein: 0, carbs: 10.6, fat: 0 },
  { name: "Cola light", aliases: ["cola zero","diet coke"], kcal: 1, protein: 0, carbs: 0, fat: 0 },
  { name: "Bier", aliases: ["pils","helles"], kcal: 43, protein: 0.5, carbs: 3.5, fat: 0, pieceGrams: 500 },
  { name: "Wein", aliases: ["rotwein","weißwein"], kcal: 85, protein: 0.1, carbs: 2.5, fat: 0, pieceGrams: 150 },
  { name: "Schokolade", aliases: ["vollmilchschokolade"], kcal: 530, protein: 7, carbs: 55, fat: 32 },
  { name: "Dunkle Schokolade", aliases: ["zartbitter"], kcal: 550, protein: 6, carbs: 45, fat: 40 },
  { name: "Gummibärchen", aliases: ["gummibaerchen"], kcal: 350, protein: 6, carbs: 80, fat: 0 },
  { name: "Chips", aliases: ["kartoffelchips"], kcal: 530, protein: 6, carbs: 50, fat: 35 },
  { name: "Eis", aliases: ["vanilleeis","eiscreme"], kcal: 200, protein: 3.5, carbs: 25, fat: 10 },
  { name: "Honig", aliases: [], kcal: 300, protein: 0.3, carbs: 82, fat: 0 },
  { name: "Marmelade", aliases: ["konfitüre"], kcal: 250, protein: 0.5, carbs: 60, fat: 0.1 },
  { name: "Nutella", aliases: ["nougatcreme"], kcal: 540, protein: 6, carbs: 57, fat: 31 },
  { name: "Müsliriegel", aliases: ["muesliriegel"], kcal: 400, protein: 6, carbs: 60, fat: 15, pieceGrams: 30 },
  { name: "Kekse", aliases: ["keks","butterkeks"], kcal: 450, protein: 6, carbs: 70, fat: 16 },
  { name: "Tomatensoße", aliases: ["tomatensosse","sugo"], kcal: 40, protein: 1.5, carbs: 7, fat: 1 },
  { name: "Pesto", aliases: [], kcal: 400, protein: 5, carbs: 5, fat: 40 },
  { name: "Ketchup", aliases: [], kcal: 100, protein: 1, carbs: 25, fat: 0.1 },
  { name: "Senf", aliases: [], kcal: 70, protein: 5, carbs: 5, fat: 4 },
  { name: "Sojasoße", aliases: ["sojasosse"], kcal: 50, protein: 6, carbs: 5, fat: 0 },
  { name: "Rührei", aliases: ["ruehrei","scrambled eggs"], kcal: 160, protein: 12, carbs: 1, fat: 12 },
  { name: "Spiegelei", aliases: ["fried egg"], kcal: 180, protein: 12, carbs: 1, fat: 14, pieceGrams: 60 },
  { name: "Omelett", aliases: ["omelette"], kcal: 170, protein: 12, carbs: 2, fat: 13 },
  { name: "Porridge", aliases: ["haferbrei"], kcal: 90, protein: 3, carbs: 15, fat: 2 },
  { name: "Overnight Oats", aliases: [], kcal: 120, protein: 5, carbs: 18, fat: 3 },
  { name: "Gebratener Reis", aliases: ["fried rice"], kcal: 180, protein: 6, carbs: 25, fat: 6 },
  { name: "Ramen", aliases: [], kcal: 120, protein: 6, carbs: 18, fat: 3 },
  { name: "Bagel", aliases: ["bagel"], kcal: 270, protein: 10, carbs: 53, fat: 1.5, pieceGrams: 90 },
  { name: "Pancake", aliases: ["pfannkuchen protein"], kcal: 220, protein: 8, carbs: 30, fat: 7, pieceGrams: 50 },
  { name: "Protein Pancake", aliases: [], kcal: 180, protein: 15, carbs: 18, fat: 5, pieceGrams: 50 },
  { name: "Sahne", aliases: ["schlagsahne"], kcal: 300, protein: 2, carbs: 3, fat: 30 },
  { name: "Saure Sahne", aliases: ["schmand"], kcal: 180, protein: 3, carbs: 4, fat: 17 },
  { name: "Ricotta", aliases: [], kcal: 170, protein: 11, carbs: 3, fat: 13 },
];

export const QUICK_FOODS = [
  { name: "Hähnchenbrust", grams: 200 },
  { name: "Ei", grams: 120 },
  { name: "Magerquark", grams: 250 },
  { name: "Haferflocken", grams: 80 },
  { name: "Reis gekocht", grams: 200 },
  { name: "Skyr", grams: 200 },
  { name: "Banane", grams: 120 },
  { name: "Proteinpulver", grams: 30 },
  { name: "Vollkornbrot", grams: 45 },
  { name: "Lachs", grams: 150 },
  { name: "Brokkoli", grams: 200 },
  { name: "Joghurt 1,5%", grams: 200 },
] as const;
