import type { FoodItem } from "@/lib/types";

export const FOOD_DB_PART1: FoodItem[] = [
  { name: "Hähnchenbrust", aliases: ["haehnchenbrust", "huhnbrust", "huhn", "chicken breast", "chicken", "haehnchen"], kcal: 165, protein: 31, carbs: 0, fat: 3.6 },
  { name: "Hähnchenschenkel", aliases: ["haehnchenschenkel", "chicken thigh"], kcal: 185, protein: 22, carbs: 0, fat: 11 },
  { name: "Putenbrust", aliases: ["pute", "truthahn", "turkey", "putenfilet"], kcal: 135, protein: 29, carbs: 0, fat: 1.5 },
  { name: "Rinderhack", aliases: ["hackfleisch", "hack", "ground beef", "gehacktes"], kcal: 250, protein: 26, carbs: 0, fat: 16 },
  { name: "Rindersteak", aliases: ["steak", "rind", "rumpsteak"], kcal: 180, protein: 27, carbs: 0, fat: 8 },
  { name: "Schweinefilet", aliases: ["schwein", "pork tenderloin"], kcal: 143, protein: 26, carbs: 0, fat: 4 },
  { name: "Lachs", aliases: ["salmon", "lachfilet"], kcal: 208, protein: 20, carbs: 0, fat: 13 },
  { name: "Thunfisch", aliases: ["tuna", "thunfisch dose"], kcal: 130, protein: 29, carbs: 0, fat: 1 },
  { name: "Garnelen", aliases: ["shrimp", "prawns"], kcal: 99, protein: 24, carbs: 0, fat: 0.3 },
  { name: "Ei", aliases: ["eier", "egg", "eggs"], kcal: 155, protein: 13, carbs: 1.1, fat: 11, pieceGrams: 60 },
  { name: "Eiklar", aliases: ["eiweiß", "eiweiss", "eiklar"], kcal: 52, protein: 11, carbs: 0.7, fat: 0.2 },
  { name: "Magerquark", aliases: ["quark", "magerquark 0%"], kcal: 67, protein: 12, carbs: 4, fat: 0.3 },
  { name: "Skyr", aliases: ["skyr nature"], kcal: 63, protein: 11, carbs: 4, fat: 0.2 },
  { name: "Haferflocken", aliases: ["hafer", "oats", "oatmeal"], kcal: 370, protein: 13, carbs: 60, fat: 7 },
  { name: "Reis gekocht", aliases: ["reis", "rice"], kcal: 130, protein: 2.7, carbs: 28, fat: 0.3 },
  { name: "Nudeln gekocht", aliases: ["pasta", "nudeln", "spaghetti"], kcal: 130, protein: 5, carbs: 25, fat: 1 },
  { name: "Kartoffel", aliases: ["kartoffeln", "potato"], kcal: 77, protein: 2, carbs: 17, fat: 0.1 },
  { name: "Vollkornbrot", aliases: ["vollkorn", "vollkornbrot"], kcal: 250, protein: 8, carbs: 45, fat: 3.5, pieceGrams: 45 },
  { name: "Banane", aliases: ["banana"], kcal: 89, protein: 1.1, carbs: 23, fat: 0.3, pieceGrams: 120 },
  { name: "Apfel", aliases: ["apple"], kcal: 52, protein: 0.3, carbs: 14, fat: 0.2, pieceGrams: 150 },
  { name: "Avocado", aliases: [], kcal: 160, protein: 2, carbs: 9, fat: 15, pieceGrams: 150 },
  { name: "Brokkoli", aliases: ["broccoli"], kcal: 34, protein: 2.8, carbs: 7, fat: 0.4 },
  { name: "Spinat", aliases: ["spinach"], kcal: 23, protein: 2.9, carbs: 3.6, fat: 0.4 },
  { name: "Tomate", aliases: ["tomaten", "tomato"], kcal: 18, protein: 0.9, carbs: 3.9, fat: 0.2 },
  { name: "Proteinpulver", aliases: ["whey", "proteinshake", "eiweißpulver"], kcal: 380, protein: 80, carbs: 6, fat: 5, pieceGrams: 30 },
  { name: "Joghurt 1,5%", aliases: ["joghurt", "yogurt"], kcal: 50, protein: 4.5, carbs: 5, fat: 1.5 },
  { name: "Mandeln", aliases: ["almonds"], kcal: 580, protein: 21, carbs: 22, fat: 50 },
  { name: "Erdnussbutter", aliases: ["peanut butter"], kcal: 590, protein: 25, carbs: 20, fat: 50 },
  { name: "Olivenöl", aliases: ["olive oil"], kcal: 884, protein: 0, carbs: 0, fat: 100 },
  { name: "Butter", aliases: [], kcal: 750, protein: 0.7, carbs: 0.6, fat: 83 },
];
