import type { FoodItem } from "@/lib/types";

export const FOOD_DB: FoodItem[] = [
  { name: "Hähnchenbrust", aliases: ["haehnchenbrust", "huhnbrust", "huhn", "chicken", "haehnchen", "hähnchen"], kcal: 165, protein: 31, carbs: 0, fat: 3.6 },
  { name: "Hähnchenschenkel", aliases: ["haehnchenschenkel", "huhnschenkel"], kcal: 185, protein: 22, carbs: 0, fat: 11 },
  { name: "Putenbrust", aliases: ["pute", "truthahn", "turkey"], kcal: 135, protein: 29, carbs: 0, fat: 1.5 },
  { name: "Rinderhack", aliases: ["hackfleisch", "hack", "hackfleisch rind"], kcal: 250, protein: 26, carbs: 0, fat: 16 },
  { name: "Rindersteak", aliases: ["steak", "rind", "rinderfilet"], kcal: 180, protein: 27, carbs: 0, fat: 8 },
  { name: "Schweinefilet", aliases: ["schwein", "schweinefleisch"], kcal: 143, protein: 21, carbs: 0, fat: 6 },
  { name: "Lachs", aliases: ["salmon"], kcal: 208, protein: 20, carbs: 0, fat: 13 },
  { name: "Thunfisch", aliases: ["tuna", "thunfischdose"], kcal: 132, protein: 29, carbs: 0, fat: 1 },
  { name: "Kabeljau", aliases: ["fisch", "weißfisch", "weissfisch"], kcal: 82, protein: 18, carbs: 0, fat: 0.7 },
  { name: "Garnelen", aliases: ["shrimp", "krebs"], kcal: 99, protein: 24, carbs: 0.2, fat: 0.3 },
  { name: "Ei", aliases: ["eier", "hühnerei", "huehnerei"], kcal: 155, protein: 13, carbs: 1.1, fat: 11, pieceGrams: 60 },
  { name: "Eiklar", aliases: ["eiweiß", "eiweiss", "egg white"], kcal: 52, protein: 11, carbs: 0.7, fat: 0.2 },
  { name: "Magerquark", aliases: ["quark", "speisequark"], kcal: 67, protein: 12, carbs: 4, fat: 0.3 },
  { name: "Skyr", aliases: ["skyr natur"], kcal: 63, protein: 11, carbs: 4, fat: 0.2 },
  { name: "Griechischer Joghurt", aliases: ["joghurt", "griechisch", "greek yogurt", "jogurt"], kcal: 97, protein: 9, carbs: 3.6, fat: 5 },
  { name: "Hüttenkäse", aliases: ["huettenkaese", "cottage"], kcal: 98, protein: 11, carbs: 3.4, fat: 4.3 },
  { name: "Milch 1,5%", aliases: ["milch", "low fat milk"], kcal: 47, protein: 3.4, carbs: 4.8, fat: 1.5 },
  { name: "Hafermilch", aliases: ["oat milk", "haferdrink"], kcal: 46, protein: 1, carbs: 6.7, fat: 1.5 },
  { name: "Proteinpulver", aliases: ["whey", "proteinshake", "shake", "protein pulver", "eiweißpulver", "eiweisspulver"], kcal: 380, protein: 80, carbs: 6, fat: 5, pieceGrams: 30 },
  { name: "Käse", aliases: ["kaese", "gouda", "schnittkäse"], kcal: 350, protein: 25, carbs: 1, fat: 27 },
  { name: "Mozzarella", aliases: ["mozzarella light"], kcal: 280, protein: 18, carbs: 2, fat: 22 },
  { name: "Feta", aliases: ["schafskäse", "schafskaese"], kcal: 264, protein: 14, carbs: 4, fat: 21 },
  { name: "Haferflocken", aliases: ["hafer", "oats", "porridge", "oatmeal"], kcal: 370, protein: 13.5, carbs: 59, fat: 7 },
  { name: "Reis gekocht", aliases: ["reis", "basmati", "reis gekocht"], kcal: 130, protein: 2.7, carbs: 28, fat: 0.3 },
  { name: "Reis roh", aliases: ["reis ungekoccht", "rohreis"], kcal: 360, protein: 7, carbs: 79, fat: 0.6 },
  { name: "Nudeln gekocht", aliases: ["nudeln", "pasta", "spaghetti", "penne"], kcal: 157, protein: 5.8, carbs: 30, fat: 0.9 },
  { name: "Nudeln roh", aliases: ["trockennudeln"], kcal: 350, protein: 13, carbs: 71, fat: 1.5 },
  { name: "Kartoffeln", aliases: ["kartoffel", "potato"], kcal: 77, protein: 2, carbs: 17, fat: 0.1 },
  { name: "Süßkartoffel", aliases: ["suesskartoffel", "sweet potato"], kcal: 86, protein: 1.6, carbs: 20, fat: 0.1 },
  { name: "Brot", aliases: ["weizenbrot", "toast", "scheibe brot"], kcal: 265, protein: 9, carbs: 49, fat: 3.2, pieceGrams: 40 },
  { name: "Vollkornbrot", aliases: ["vollkorn", "graubrot"], kcal: 250, protein: 8, carbs: 43, fat: 3.5, pieceGrams: 45 },
  { name: "Brötchen", aliases: ["broetchen", "semmel"], kcal: 270, protein: 8, carbs: 52, fat: 2.5, pieceGrams: 60 },
  { name: "Reiswaffeln", aliases: ["reiswaffel"], kcal: 390, protein: 8, carbs: 82, fat: 3, pieceGrams: 8 },
  { name: "Banane", aliases: ["bananen"], kcal: 89, protein: 1.1, carbs: 23, fat: 0.3, pieceGrams: 120 },
  { name: "Apfel", aliases: ["äpfel", "aepfel", "apples"], kcal: 52, protein: 0.3, carbs: 14, fat: 0.2, pieceGrams: 160 },
  { name: "Orange", aliases: ["apfelsine"], kcal: 47, protein: 0.9, carbs: 12, fat: 0.1, pieceGrams: 150 },
  { name: "Beeren", aliases: ["erdbeeren", "heidelbeeren", "himbeeren", "blaubeeren"], kcal: 43, protein: 1, carbs: 8, fat: 0.4 },
  { name: "Avocado", aliases: ["avos"], kcal: 160, protein: 2, carbs: 9, fat: 15, pieceGrams: 150 },
  { name: "Brokkoli", aliases: ["broccoli"], kcal: 34, protein: 2.8, carbs: 7, fat: 0.4 },
  { name: "Spinat", aliases: ["spinach"], kcal: 23, protein: 2.9, carbs: 3.6, fat: 0.4 },
  { name: "Gurke", aliases: ["salatgurke"], kcal: 15, protein: 0.6, carbs: 3.6, fat: 0.1 },
  { name: "Tomate", aliases: ["tomaten"], kcal: 18, protein: 0.9, carbs: 3.9, fat: 0.2 },
  { name: "Paprika", aliases: ["peperoni"], kcal: 31, protein: 1, carbs: 6, fat: 0.3 },
  { name: "Zwiebel", aliases: ["zwiebeln"], kcal: 40, protein: 1.1, carbs: 9, fat: 0.1 },
  { name: "Salat", aliases: ["gemischter salat", "eisbergsalat"], kcal: 15, protein: 1.2, carbs: 2.9, fat: 0.2 },
  { name: "Olivenöl", aliases: ["oel", "öl", "olive oil"], kcal: 884, protein: 0, carbs: 0, fat: 100 },
  { name: "Butter", aliases: ["butterstück"], kcal: 717, protein: 0.9, carbs: 0.1, fat: 81 },
  { name: "Erdnussbutter", aliases: ["peanut butter", "erdnussmus"], kcal: 588, protein: 25, carbs: 20, fat: 50 },
  { name: "Mandeln", aliases: ["mandel"], kcal: 579, protein: 21, carbs: 22, fat: 50 },
  { name: "Walnüsse", aliases: ["walnuss", "nüsse", "nuesse"], kcal: 654, protein: 15, carbs: 14, fat: 65 },
  { name: "Reiscracker", aliases: [], kcal: 390, protein: 8, carbs: 80, fat: 3 },
  { name: "Schokolade", aliases: ["schoko", "milchschokolade"], kcal: 535, protein: 8, carbs: 59, fat: 30 },
  { name: "Dunkle Schokolade", aliases: ["zartbitter"], kcal: 598, protein: 8, carbs: 46, fat: 43 },
  { name: "Cola", aliases: ["coke", "softdrink"], kcal: 42, protein: 0, carbs: 10.6, fat: 0 },
  { name: "Apfelsaft", aliases: ["saft"], kcal: 46, protein: 0.1, carbs: 11, fat: 0.1 },
  { name: "Kaffee", aliases: ["espresso", "americano"], kcal: 2, protein: 0.1, carbs: 0, fat: 0 },
  { name: "Proteinriegel", aliases: ["riegel", "protein bar"], kcal: 360, protein: 30, carbs: 28, fat: 12, pieceGrams: 60 },
  { name: "Döner", aliases: ["doener", "kebab", "kebap"], kcal: 230, protein: 13, carbs: 20, fat: 11, pieceGrams: 350 },
  { name: "Pizza", aliases: ["salami pizza", "margherita"], kcal: 266, protein: 11, carbs: 33, fat: 10, pieceGrams: 300 },
  { name: "Pommes", aliases: ["frites", "french fries"], kcal: 312, protein: 3.4, carbs: 41, fat: 15 },
  { name: "Burger", aliases: ["hamburger", "cheeseburger"], kcal: 250, protein: 13, carbs: 22, fat: 12, pieceGrams: 220 },
  { name: "Currywurst", aliases: ["wurst"], kcal: 280, protein: 12, carbs: 18, fat: 18, pieceGrams: 200 },
  { name: "Leberkäse", aliases: ["leberkaese", "leberkas"], kcal: 310, protein: 13, carbs: 2, fat: 28, pieceGrams: 150 },
  { name: "Thunfischsalat", aliases: [], kcal: 120, protein: 16, carbs: 3, fat: 5 },
  { name: "Couscous gekocht", aliases: ["couscous"], kcal: 112, protein: 3.8, carbs: 23, fat: 0.2 },
  { name: "Quinoa gekocht", aliases: ["quinoa"], kcal: 120, protein: 4.4, carbs: 21, fat: 1.9 },
  { name: "Linsen gekocht", aliases: ["linsen"], kcal: 116, protein: 9, carbs: 20, fat: 0.4 },
  { name: "Kichererbsen", aliases: ["chickpeas"], kcal: 164, protein: 8.9, carbs: 27, fat: 2.6 },
  { name: "Tofu", aliases: ["soja"], kcal: 76, protein: 8, carbs: 1.9, fat: 4.8 },
  { name: "Lachsfilet gebraten", aliases: [], kcal: 230, protein: 25, carbs: 0, fat: 14 },
  { name: "Thunfisch in Wasser", aliases: ["dosen thunfisch"], kcal: 86, protein: 19, carbs: 0, fat: 1 },
  { name: "Mozzarella light", aliases: [], kcal: 161, protein: 19, carbs: 1, fat: 9 },
  { name: "Cornflakes", aliases: ["müsli", "muesli", "cereal"], kcal: 357, protein: 7, carbs: 84, fat: 0.9 },
  { name: "Honig", aliases: ["honey"], kcal: 304, protein: 0.3, carbs: 82, fat: 0 },
  { name: "Marmelade", aliases: ["konfitüre", "konfituere"], kcal: 250, protein: 0.4, carbs: 62, fat: 0.1 },
  { name: "Nutella", aliases: ["nougatcreme"], kcal: 539, protein: 6, carbs: 57, fat: 31 },
  { name: "Croissant", aliases: ["hörnchen", "hoernchen"], kcal: 406, protein: 8, carbs: 45, fat: 21, pieceGrams: 60 },
  { name: "Pancake", aliases: ["pfannkuchen", "eierkuchen"], kcal: 227, protein: 6, carbs: 28, fat: 10, pieceGrams: 80 },
  { name: "Whey Isolate", aliases: ["isolate"], kcal: 370, protein: 90, carbs: 2, fat: 1, pieceGrams: 30 },
  { name: "Casein", aliases: ["kasein"], kcal: 360, protein: 78, carbs: 6, fat: 2, pieceGrams: 30 },
  { name: "Creatin", aliases: ["kreatin", "creatine"], kcal: 0, protein: 0, carbs: 0, fat: 0, pieceGrams: 5 },
  { name: "Wasser", aliases: ["mineralwasser"], kcal: 0, protein: 0, carbs: 0, fat: 0 },
  { name: "Red Bull", aliases: ["energydrink", "energy drink"], kcal: 45, protein: 0, carbs: 11, fat: 0 },
  { name: "Bier", aliases: ["pils", "weizen"], kcal: 43, protein: 0.5, carbs: 3.6, fat: 0 },
  { name: "Wein", aliases: ["rotwein", "weißwein", "weisswein"], kcal: 83, protein: 0.1, carbs: 2.6, fat: 0 },
  { name: "Reisnudeln", aliases: [], kcal: 109, protein: 0.9, carbs: 25, fat: 0.2 },
  { name: "Wrap", aliases: ["tortilla", "wraps"], kcal: 300, protein: 8, carbs: 50, fat: 7, pieceGrams: 60 },
  { name: "Tortilla", aliases: ["weizentortilla"], kcal: 300, protein: 8, carbs: 50, fat: 7, pieceGrams: 60 },
  { name: "Hummus", aliases: ["humus"], kcal: 166, protein: 8, carbs: 14, fat: 10 },
  { name: "Guacamole", aliases: [], kcal: 150, protein: 2, carbs: 8, fat: 13 },
  { name: "Ketchup", aliases: [], kcal: 112, protein: 1.2, carbs: 25, fat: 0.1 },
  { name: "Mayonnaise", aliases: ["mayo"], kcal: 680, protein: 1, carbs: 1, fat: 75 },
  { name: "Salatsoße", aliases: ["dressing", "salatdressing"], kcal: 230, protein: 0.5, carbs: 6, fat: 23 },
  { name: "Parmesan", aliases: [], kcal: 431, protein: 38, carbs: 4, fat: 29 },
  { name: "Bacon", aliases: ["speck", "frühstücksspeck", "fruehstuecksspeck"], kcal: 541, protein: 37, carbs: 1.4, fat: 42 },
  { name: "Schinken", aliases: ["kochschinken", "putenschinken"], kcal: 110, protein: 21, carbs: 1, fat: 3 },
  { name: "Salami", aliases: [], kcal: 378, protein: 22, carbs: 1, fat: 32 },
  { name: "Wiener", aliases: ["würstchen", "wuerstchen", "hot dog"], kcal: 280, protein: 12, carbs: 1, fat: 25, pieceGrams: 50 },
  { name: "Maultaschen", aliases: [], kcal: 180, protein: 8, carbs: 22, fat: 6 },
  { name: "Spätzle", aliases: ["spaetzle"], kcal: 200, protein: 7, carbs: 32, fat: 5 },
  { name: "Knödel", aliases: ["knoedel", "semmelknödel"], kcal: 150, protein: 4, carbs: 24, fat: 4 },
  { name: "Gnocchi", aliases: [], kcal: 160, protein: 4, carbs: 32, fat: 1 },
  { name: "Sushi", aliases: ["maki", "nigiri"], kcal: 150, protein: 6, carbs: 28, fat: 1.5, pieceGrams: 25 },
  { name: "Ramen", aliases: [], kcal: 90, protein: 4, carbs: 14, fat: 2 },
  { name: "Falafel", aliases: [], kcal: 333, protein: 13, carbs: 32, fat: 18, pieceGrams: 25 },
  { name: "Gyros", aliases: [], kcal: 220, protein: 18, carbs: 4, fat: 14 },
  { name: "Reisbowl", aliases: ["bowl", "poke"], kcal: 140, protein: 8, carbs: 18, fat: 4 },
  { name: "Magerjoghurt", aliases: ["joghurt 0%", "naturjoghurt"], kcal: 45, protein: 5, carbs: 6, fat: 0.1 },
  { name: "Kefir", aliases: [], kcal: 55, protein: 3, carbs: 4.5, fat: 2 },
  { name: "Mozzarella-Stick", aliases: [], kcal: 318, protein: 15, carbs: 22, fat: 18 },
  { name: "Chicken Nuggets", aliases: ["nuggets"], kcal: 296, protein: 16, carbs: 15, fat: 19 },
  { name: "Fischstäbchen", aliases: ["fischstaebchen"], kcal: 190, protein: 12, carbs: 16, fat: 8, pieceGrams: 30 },
  { name: "Erbsen", aliases: [], kcal: 81, protein: 5, carbs: 14, fat: 0.4 },
  { name: "Mais", aliases: ["corn"], kcal: 86, protein: 3.3, carbs: 19, fat: 1.2 },
  { name: "Bohnen", aliases: ["weiße bohnen", "weisse bohnen"], kcal: 81, protein: 6, carbs: 10, fat: 0.5 },
  { name: "Karotte", aliases: ["möhre", "moehre", "karotten"], kcal: 41, protein: 0.9, carbs: 10, fat: 0.2 },
  { name: "Zucchini", aliases: [], kcal: 17, protein: 1.2, carbs: 3.1, fat: 0.3 },
  { name: "Champignons", aliases: ["pilze", "mushroom"], kcal: 22, protein: 3.1, carbs: 3.3, fat: 0.3 },
  { name: "Blaubeeren", aliases: ["heidelbeere"], kcal: 57, protein: 0.7, carbs: 14, fat: 0.3 },
  { name: "Trauben", aliases: ["weintrauben"], kcal: 69, protein: 0.7, carbs: 18, fat: 0.2 },
  { name: "Birne", aliases: [], kcal: 57, protein: 0.4, carbs: 15, fat: 0.1, pieceGrams: 170 },
  { name: "Kiwi", aliases: [], kcal: 61, protein: 1.1, carbs: 15, fat: 0.5, pieceGrams: 75 },
  { name: "Mango", aliases: [], kcal: 60, protein: 0.8, carbs: 15, fat: 0.4 },
  { name: "Ananas", aliases: [], kcal: 50, protein: 0.5, carbs: 13, fat: 0.1 },
  { name: "Wassermelone", aliases: ["melone"], kcal: 30, protein: 0.6, carbs: 8, fat: 0.2 },
  { name: "Cranberry", aliases: [], kcal: 46, protein: 0.4, carbs: 12, fat: 0.1 },
  { name: "Datteln", aliases: ["dattel"], kcal: 277, protein: 2, carbs: 75, fat: 0.2, pieceGrams: 8 },
  { name: "Rosinen", aliases: [], kcal: 299, protein: 3, carbs: 79, fat: 0.5 },
  { name: "Chiasamen", aliases: ["chia"], kcal: 486, protein: 17, carbs: 42, fat: 31 },
  { name: "Leinsamen", aliases: [], kcal: 534, protein: 18, carbs: 29, fat: 42 },
  { name: "Proteinpudding", aliases: ["high protein pudding"], kcal: 80, protein: 10, carbs: 6, fat: 1.5, pieceGrams: 200 },
  { name: "Milchreis", aliases: [], kcal: 130, protein: 3.5, carbs: 22, fat: 3 },
  { name: "Kartoffelpüree", aliases: ["kartoffelpüree", "püree", "puree"], kcal: 83, protein: 2, carbs: 13, fat: 2.8 },
  { name: "Ofenkartoffel", aliases: [], kcal: 93, protein: 2.5, carbs: 21, fat: 0.1, pieceGrams: 200 },
];

export const QUICK_FOODS = [
  { name: "Hähnchenbrust", grams: 200 },
  { name: "Ei", grams: 120 },
  { name: "Magerquark", grams: 250 },
  { name: "Haferflocken", grams: 80 },
  { name: "Reis gekocht", grams: 200 },
  { name: "Skyr", grams: 200 },
  { name: "Banane", grams: 120 },
  { name: "Proteinpulver", grams: 30 },
] as const;
